from .elliptic import TestElliptic
from .VortexCylinder import TestCylinder
from .VortexRing import TestRing
from .VortexDoublet import TestDoublet
from .VortexCylinderSkewed import TestSkewedCylinder
from .VortexLine import TestVortexLine
from .WindFarm import TestWindFarm
from .Solver import TestSolver
from .WindTurbine import TestWindTurbine
